---
- name: Get Device Facts and Configuration
  hosts: junos_devices # Replace with your inventory group
  connection: junipernetworks.junos.pyez # Or connection: local
  gather_facts: no # Prevents gathering facts for the control node

  tasks:
    - name: Retrieve Junos device facts and configuration
      junipernetworks.junos.junos_facts:
        config_format: xml # Or 'json', 'set', 'text'
      register: device_info

    - name: Print retrieved facts and configuration
      debug:
        var: device_info.ansible_facts.junos
